import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./_components/sections/Footer";
import { cn } from "@/lib/utils";
import Header from "./_components/sections/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative">
      <body className={cn(inter.className, "antialiased bg-background ")}>
    
          <Header />

          {children}
      
      </body>
    </html>
  );
}
